### PR TITLE
Annulus-97 

### PR DESCRIPTION
**Pull request by Kelz29**
More refactoring happening on ANNULUS-124 - Clean up 

Screenshot 2023-04-25 at 14 11 47
Screenshot 2023-04-25 at 14 11 33
Screenshot 2023-04-25 at 14 11 21
Screenshot 2023-04-25 at 14 11 08

### CODE REVIEW

**Review by KalervoHyyppa — CHANGES_REQUESTED** [review]
Still reviewing. Hold off merging or approving until the new folder structure is set up

**Comment by Kelz29** [comment]
> Still reviewing. Hold off merging or approving until the new folder structure is set up

Sweet I'll hold off

**Comment by KalervoHyyppa** [comment]
When you get a chance, please resolve merge conflicts

**Comment by Kelz29** [comment]
> 

Sweet let me sort them out.

**Pull request closed without merging**
